// create constructor with type hitpoints and defense
// create a function to select random enemy type
// create a function to generate hit points randomly according to parameters
// enemy defense is generated by multiplying the hitpoints by 3

var enemies = ["Ancient Dragon", "Prowler", "Mighty Grunt"];

function enemyType() {
    var roll = Math.round(Math.random() * 2)
    return enemies[roll];
}

function hitPoints() {
    var enemy = enemyType();
    var hitPoints = 0;
    if (enemy == "Ancient Dragon") {
        hitPoints = Math.floor(Math.random() * (80 - 100) + 80);
    } else if (enemy == "Prowler") {
        hitPoints = Math.floor(Math.random() * (50 - 79) + 50);
    } else {
        hitPoints = Math.floor(Math.random() * (20 - 49) + 49);
    }
    return hitPoints;
}

//console.log(hitPoints());

function enemyDef() {
    var points = hitPoints();
    var defense = points * 3;
    return defense;
}

//console.log(enemyDef());

function generateEnemy(num) {
    for (var i = 1; i <= num; i++) {
        var enemy = enemyType();
        var hitpoints = hitPoints();
        var defense = enemyDef();
        console.log("Enemy " + i + " is a: " + enemy + " and has " + hitpoints + " hit points and " + defense + " defense points!");
    }
}

generateEnemy(100);